services:
  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      - redis
    networks:
      - ticketnet
  redis:
    image: redis:7-alpine
    command: redis-server --notify-keyspace-events Ex
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    networks:
      - ticketnet
volumes:
  redis-data:
networks:
  ticketnet:
    driver: bridge
