services:
  app:
    build: .
    command: npm run watch
    ports:
      - "3000:3000"
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      - redis
    volumes:
      - .:/app
    networks:
      - fabacusnet
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    networks:
      - fabacusnet
volumes:
  redis-data:
networks:
  fabacusnet:
    driver: bridge
