openapi: 3.0.4
info:
  title: Online Reservation System API
  version: 1.0.0
  description: API for managing events and seat reservations
servers:
  - url: http://localhost:3000
paths:
  /events/create:
    post:
      summary: Create a new event
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  description: Name of the event
                totalSeats:
                  type: integer
                  minimum: 10
                  maximum: 10000
                  description: Total number of seats for the event (10-10,000)
              required:
                - name
                - totalSeats
      responses:
        "201":
          description: Event created successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
                    description: Unique identifier for the event
                  name:
                    type: string
                    description: Name of the event
                  totalSeats:
                    type: integer
                    description: Total number of seats for the event
        "400":
          description: Invalid event data
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
        "500":
          description: Internal server error
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
  /events/{id}:
    get:
      summary: Get event by ID
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        "200":
          description: Event found
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
                  name:
                    type: string
                  totalSeats:
                    type: integer
        "404":
          description: Event not found
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
        "500":
          description: Internal server error
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
  /seats/get/{id}:
    get:
      summary: Get seat by ID
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        "200":
          description: Seat found
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
                  eventId:
                    type: string
                  UUID:
                    type: string
                  status:
                    type: string
                    enum: ["Available", "On hold", "Reserved"]
        "404":
          description: Seat not found
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
        "500":
          description: Internal server error
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
  /seats/list/{eventId}:
    get:
      summary: List available seats for an event
      parameters:
        - name: eventId
          in: path
          required: true
          schema:
            type: string
      responses:
        "200":
          description: List of available seats with event details
          content:
            application/json:
              schema:
                type: object
                properties:
                  total:
                    type: integer
                    description: Total number of available seats
                  event:
                    type: object
                    properties:
                      id:
                        type: string
                      name:
                        type: string
                      totalSeats:
                        type: integer
                  seats:
                    type: array
                    items:
                      type: object
                      properties:
                        id:
                          type: string
                        eventId:
                          type: string
                        UUID:
                          type: string
                        status:
                          type: string
                          enum: ["Available", "On hold", "Reserved"]
        "500":
          description: Internal server error
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
  /seats/hold:
    post:
      summary: Hold a seat for a configured amount of time
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                id:
                  type: string
                  description: Unique identifier for the seat
                UUID:
                  type: string
                  description: Unique identifier for the user holding the seat
              required:
                - id
                - UUID
      responses:
        "200":
          description: Seat held successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                  seat:
                    type: object
                    properties:
                      id:
                        type: string
                      eventId:
                        type: string
                      UUID:
                        type: string
                      status:
                        type: string
                        enum: ["Available", "On hold", "Reserved"]
        "404":
          description: Seat not found
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
        "409":
          description: Seat not available
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
        "423":
          description: Seat is already locked
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
        "429":
          description: Max held seats reached
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
        "500":
          description: Internal server error
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
  /seats/hold/refresh:
    post:
      summary: Refresh hold on a seat, restarting the lock expiration timer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                id:
                  type: string
                  description: Seat ID
                UUID:
                  type: string
                  description: User UUID that must match the held seat
              required:
                - id
                - UUID
      responses:
        "200":
          description: Seat hold refreshed successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
        "403":
          description: UUID does not match held seat
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
        "404":
          description: Seat not found
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
        "409":
          description: Seat is not On hold
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
        "500":
          description: Internal server error
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
  /seats/reserve:
    post:
      summary: Reserve a seat (must be On hold and UUID must match)
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                id:
                  type: string
                  description: Seat ID
                UUID:
                  type: string
                  description: User UUID that must match the held seat
              required:
                - id
                - UUID
      responses:
        "200":
          description: Seat reserved successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                  seat:
                    type: object
                    properties:
                      id:
                        type: string
                      eventId:
                        type: string
                      UUID:
                        type: string
                      status:
                        type: string
                        enum: ["Available", "On hold", "Reserved"]
        "403":
          description: Seat is not On hold or UUID mismatch
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
        "404":
          description: Seat not found
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
        "500":
          description: Internal server error
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
components:
  schemas:
    Event:
      type: object
      properties:
        id:
          type: string
          description: Unique identifier for the event
        name:
          type: string
          description: Name of the event
        totalSeats:
          type: integer
          description: Total number of seats for the event
      required:
        - id
        - name
        - totalSeats
    Seat:
      type: object
      properties:
        id:
          type: string
          description: Unique identifier for the seat
        eventId:
          type: string
          description: References the event's ID
        UUID:
          type: string
          description: References the user's UUID (empty if not held)
        status:
          type: string
          enum: ["Available", "On hold", "Reserved"]
          description: Current status of the seat
      required:
        - id
        - eventId
        - UUID
        - status
    Error:
      type: object
      properties:
        error:
          type: string
          description: Error message
      required:
        - error
